version: "1.0"  # optional since v1.27.0
services:
  swgemu:
    build: .
    ports:
      - "44455:44455"
      - "44419:44419"
      - "44462:44462/udp"
      - "44463:44463/udp"
      - "44453:44453/udp"
    expose:
      - "44455"
      - "44419"
      - "44462/udp"
      - "44463/udp"
      - "44453/udp"
    depends_on:
      - mysql
    volumes:
      - ./Core3/MMOCoreORB/bin/databases/:/work/Core3/MMOCoreORB/bin/databases/
      - ./Core3/MMOCoreORB/bin/log/:/work/Core3/MMOCoreORB/bin/log/
      - ./Core3/MMOCoreORB/bin/scripts/managers/resource_manager_spawns.lua:/work/Core3/MMOCoreORB/bin/scripts/managers/resource_manager_spawns.lua
      - ./SWGEmu-tre-files/:/home/swgemu/Desktop/SWGEmu
      - .:/work
    command: /work/Core3/MMOCoreORB/bin/core3
    working_dir: /work/Core3/MMOCoreORB/bin/
  mysql:
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql/
    image: mysql
